# Generated by Django 3.1.5 on 2021-02-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributeur',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='contributeur',
            old_name='user_id',
            new_name='user',
        ),
    ]
